name: Node.js Docker CI/CD
on:
  push:
    branches: [ main ]

jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout repo
        uses: actions/checkout@v3   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node-docker-app-2:latest
      - name: Setup kubeconfig
        run: | 
          echo: "${{ secrets.EKS_CLUSTER_NAME }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
